# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Justin Boyson dot com
tagline:          'A Jekyll theme'
description:      'A static blog about building a static blog. Using the excellent <a href="http://hyde.getpoole.com/">Hyde</a> theme.'
url:              http://justinboyson.com
baseurl:          /

author:
  name:           'Justin Boyson'
  url:            https://twitter.com/unclejustin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]
