# Site settings
title: Justin Boyson dot com
email: justin@justinboyson.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog/playground for Justin Boyson,
  UI/X, Front End Developer and all around nice guy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://unclejustin.github.com" # the base hostname & protocol for your site
twitter_username: unclejustin
github_username:  unclejustin

# Build settings
markdown: kramdown
